---
sidebar: sidebar 
permalink: integrations/dashboard-overview.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, NetApp Console, Console 
summary: In qualità di abbonato a NetApp Keystone STaaS, puoi ottenere una panoramica dei tuoi abbonamenti da NetApp Console o Digital Advisor. 
---
= Scopri di più sulla dashboard Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La dashboard Keystone è la soluzione ideale per monitorare, analizzare e gestire in modo efficiente i tuoi abbonamenti Keystone .  Attraverso la dashboard Keystone è possibile raggiungere i seguenti obiettivi:

* *Monitoraggio dei dettagli dell'abbonamento*: visualizza informazioni dettagliate sui tuoi abbonamenti Keystone , inclusi livelli di servizio delle prestazioni, utilizzo della capacità, risorse e avvisi.
* *Monitorare l'utilizzo della capacità e generare report*: tenere traccia dell'utilizzo attuale e storico della capacità e generare report per analizzare i dati degli abbonamenti e prendere decisioni informate.
* *Visualizza la cronologia degli abbonamenti*: rimani informato sulle date e gli eventi più importanti monitorando la cronologia dei tuoi abbonamenti.
* *Gestisci abbonamenti*: invia richieste per modificare i livelli di servizio delle prestazioni o altri parametri di abbonamento in base alle tue esigenze.
* *Analizza volumi e oggetti*: ottieni informazioni dettagliate sui volumi e sugli oggetti dei tuoi abbonamenti, inclusa la loro capacità sia a livello di volume che di oggetto.




== Accedi alla dashboard Keystone

È possibile accedere alla dashboard Keystone tramite:

* * Console NetApp *: accedi alla dashboard da *Storage > Keystone > Panoramica* nella Console. Per saperne di più, fare riferimento alink:../integrations/keystone-console.html["Dashboard Keystone nella console NetApp"^] .
* * Digital Advisor Active IQ * (noto anche come Digital Advisor): accedi alla dashboard da *Generale > Abbonamenti Keystone * in Digital Advisor.  Per saperne di più, fare riferimento alink:../integrations/keystone-aiq.html["Dashboard Keystone in Digital Advisor"^] .




== Informazioni su NetApp Console

Keystone è accessibile tramite la console NetApp .

NetApp Console offre una gestione centralizzata dei servizi di archiviazione e dati NetApp in ambienti on-premise e cloud su scala aziendale. La console è necessaria per accedere e utilizzare i servizi dati NetApp . In quanto interfaccia di gestione, consente di gestire numerose risorse di archiviazione da un'unica interfaccia. Gli amministratori della console possono controllare l'accesso allo storage e ai servizi per tutti i sistemi all'interno dell'azienda.

Per iniziare a utilizzare la Console non è necessaria una licenza o un abbonamento e verranno addebitati dei costi solo quando sarà necessario distribuire gli agenti della Console nel cloud per garantire la connettività ai sistemi di storage o ai servizi dati NetApp . Tuttavia, alcuni servizi dati NetApp accessibili dalla Console sono concessi in licenza o basati su abbonamento.

Scopri di più sulink:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Console NetApp"^] .

Notare quanto segue:

* Sebbene la Console e Digital Advisor offrano alcune funzionalità esclusive, la Console fornisce funzionalità amministrative per Keystone, consentendo di gestire gli abbonamenti e apportare le modifiche necessarie. Per ulteriori informazioni, consultare link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-keystone-roles.html["Ruoli di accesso Keystone nella NetApp Console"^].
* Digital Advisor è integrato con la Console, consentendoti di accedere a tutte le funzionalità Digital Advisor , inclusa la dashboard Keystone , direttamente dalla Console. Per saperne di più, fare riferimento alink:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-console.html#netapp-console["Integrazione Digital Advisor con NetApp Console"^] .




== Funzionalità Keystone in NetApp Console e Digital Advisor

La tabella seguente mostra la disponibilità delle funzionalità nella NetApp Console e in Digital Advisor, aiutandoti a identificare rapidamente la piattaforma più adatta alle tue esigenze:

|===


| *Caratteristica* | * Console NetApp * | * Digital Advisor* 


 a| 
link:../integrations/subscriptions-tab.html["Visualizza i dettagli del tuo abbonamento"]
| SÌ | SÌ 


 a| 
link:../integrations/current-usage-tab.html["Monitorare l'utilizzo della capacità attuale e storica"]
| SÌ | SÌ 


 a| 
link:../integrations/subscription-timeline.html["Tieni traccia della cronologia degli abbonamenti"]
| SÌ | NO 


 a| 
link:../integrations/assets-tab.html["Visualizza le risorse associate a un abbonamento Keystone"]
| SÌ | SÌ 


| link:../integrations/assets.html["Visualizza le risorse su più abbonamenti Keystone"] | SÌ | NO 


 a| 
link:../integrations/monitoring-alerts.html["Visualizza e gestisci avvisi e monitor"]
| SÌ | NO 


 a| 
link:../integrations/options.html#generate-reports-from-netapp-console-or-digital-advisor["Generare report"]
| SÌ | SÌ 


 a| 
link:../integrations/volumes-objects-tab.html["Visualizza i dettagli dei volumi e degli oggetti"]
| SÌ | SÌ 


 a| 
link:../integrations/adp-tab.html["Visualizza il consumo e lo stato di integrità di MetroCluster"]
| Sì (include stato di integrità, visualizzazione della topologia e monitoraggio della sincronizzazione) | Sì (solo dati di consumo) 


 a| 
link:../integrations/performance-tab.html["Visualizza le metriche delle prestazioni"]
| NO | SÌ 
|===
*Informazioni correlate*

* link:../integrations/dashboard-access.html["Inizia con la dashboard Keystone"]
* link:../integrations/keystone-console.html["Dashboard Keystone nella console NetApp"]
* link:..//integrations/keystone-aiq.html["Dashboard Keystone in Digital Advisor"]

