---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Gli abbonamenti Keystone STaaS vengono fatturati mensilmente e annualmente. 
---
= Piani di fatturazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Gli abbonamenti Keystone STaaS vengono fatturati su base mensile o annuale.



== Fatturazione mensile

Le fatture vengono inviate mensilmente.  Per il mese in cui si usufruisce dei servizi, la fattura viene inviata il mese successivo.  Ad esempio, la fattura per i servizi utilizzati a gennaio viene consegnata all'inizio di febbraio.  Questa fattura include gli addebiti per la capacità impegnata e, se applicabile, eventuali utilizzi eccessivi.



== Fatturazione annuale

All'inizio di ogni anno di abbonamento viene generata una fattura per il pagamento minimo della capacità impegnata.  Viene generato alla data di inizio dell'abbonamento.  Un'altra fattura viene inviata alla fine di un trimestre di abbonamento, riepilogando gli addebiti applicabili per qualsiasi utilizzo eccessivo maturato in quel trimestre.  Se la capacità impegnata viene modificata durante un abbonamento, lo stesso giorno verrà inviata una fattura per i pagamenti minimi ripartiti per il resto dell'anno di abbonamento.  La fatturazione viene calcolata a partire dal giorno in cui la modifica della capacità impegnata diventa effettiva.
