---
sidebar: sidebar 
permalink: concepts/burst-consumption-billing.html 
keywords: burst consumption billing 
summary: La fatturazione di Keystone STaaS si basa sulla capacità di picco, ovvero la capacità da te consumata, in aggiunta alla capacità impegnata del tuo abbonamento. 
---
= Comprendere la fatturazione dei consumi a raffica Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La fatturazione di Keystone STaaS si basa sulla _capacità massima_, ovvero la capacità da te consumata, in aggiunta alla capacità impegnata del tuo abbonamento.

Il limite di burst è determinato e specificato nel contratto Keystone .  È superiore del 20% alla capacità impegnata.

La capacità impegnata è la capacità che ti è stata assegnata al momento dell'acquisto dell'abbonamento.  La capacità impegnata e la capacità di burst vengono misurate in base al livello di servizio delle prestazioni.  La capacità consumata è la capacità effettivamente utilizzata dai carichi di lavoro.

Quando la capacità consumata è maggiore della capacità impegnata per un livello di servizio prestazionale, il consumo di picco viene registrato e addebitato di conseguenza.  Di solito è superiore del 20% alla capacità impegnata.  L'utilizzo al di sopra della capacità di burst è indicato come "Sopra il limite di burst".

Questo processo si verifica per ogni record di consumo generato.  Il consumo a raffica, quindi, riflette sia la quantità che la durata delle capacità sovraconsumate rispetto alle capacità impegnate.  Per saperne di più, fare riferimento alink:../integrations/consumption-tab.html["Visualizza le tendenze di consumo dei tuoi abbonamenti Keystone"] .

Per informazioni sulle diverse capacità supportate in Keystone, vederelink:../concepts/supported-storage-capacity.html["Capacità di archiviazione supportate in Keystone"] .
