---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS offre capacità di archiviazione a livelli di servizio predefiniti.  A ciascun volume gestito da Keystone è associato un livello di servizio. 
---
= Livelli di servizio prestazionali a Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS offre capacità di archiviazione dati a livelli di servizio prestazionali predefiniti.  A ciascun volume gestito dai servizi Keystone è associato un livello di servizio prestazionale.

Un abbonamento può avere più piani tariffari e ogni piano tariffario corrisponde a un livello di servizio prestazionale.  Ogni piano tariffario prevede una capacità impegnata per livello di servizio prestazionale.

Ogni livello di servizio prestazionale è definito dalla sua densità I/O, ovvero IOPS/TiB/volume.  Si tratta del rapporto tra prestazioni (operazioni di input/output al secondo [IOPS]) e capacità di archiviazione utilizzata (TiB), ovvero IOPS/TiB alla latenza media per volume.

È possibile selezionare i livelli di servizio delle prestazioni in base al proprio ambiente di archiviazione e alle esigenze di archiviazione e consumo.  I livelli di servizio delle prestazioni di base sono disponibili per impostazione predefinita.  Sono inoltre disponibili livelli di servizio di prestazioni specifici, se hai optato per servizi aggiuntivi.  Ad esempio, per il servizio aggiuntivo di protezione avanzata dei dati, al tuo abbonamento viene assegnato il livello di servizio prestazionale _Advanced Data-Protect_.


TIP: È disponibile una descrizione dettagliata del servizio per i livelli di servizio delle prestazioni NetApp Keystone STaaS https://www.netapp.com/services/keystone/terms-and-conditions/["Qui"^] .

I livelli di servizio delle prestazioni di base per i tipi di archiviazione supportati, file, blocchi, oggetti e servizi cloud sono descritti nelle sezioni seguenti:



== Livelli di servizio prestazionali per l'archiviazione di file e blocchi

*Protocolli supportati*: NFS, CIFS, iSCSI e FC

|===


| *Livello di servizio prestazionale* | *Estremo* | *Premium* | *Prestazione* | *Standard* | *Valore* 


| *Esempi di tipi di carico di lavoro* | Analisi, database, app mission-critical | VDI, VSI, sviluppo software | OLTP, OLAP, contenitori, sviluppo software | Condivisioni di file, server web | Backup 


| *IOPS massimi/TiB logici archiviati per volume* | 12.288 | 4.096 | 2.048 | 512 | 128 


| *IOPS massimi/TiB logici assegnati per volume* | 6.144 | 2.048 | 1.024 | 256 | 64 


| *Massimo MBps/TiB logici archiviati per volume a 32K B/S* | 384 | 128 | 64 | 16 | 4 


| *Obiettivo di latenza del 90° percentile* | <1 millisecondo | <2 millisecondi | <4 millisecondi | <4 millisecondi | <17 ms 


| *Dimensione del blocco* 5+| 32K 


| *Tipo di capacità impegnata e misurata* 5+| Logico 
|===


=== Ulteriori informazioni sui livelli di servizio delle prestazioni per l'archiviazione di file e blocchi

Le metriche del livello di servizio delle prestazioni di base dipendono dalle seguenti condizioni:

* I livelli di servizio delle prestazioni per l'archiviazione di file e blocchi supportano ONTAP 9.7 e versioni successive.
* I valori IOPS/TiB/volume, MBps/TiB/volume e latenza per i livelli di servizio delle prestazioni si basano sulla quantità di dati archiviati nel volume, sulla dimensione del blocco di 32 KB e su una combinazione casuale del 70% di operazioni di I/O in lettura e del 30% in scrittura.
* Gli IOPS/TiB/volume effettivi e MBps/TiB/volume possono variare in base alle dimensioni effettive o presunte del blocco, alla concorrenza del carico di lavoro del sistema o alle operazioni di input-output.
* La latenza non include quanto segue:
+
** latenza dell'applicazione o dell'host
** latenza della rete del cliente da o verso le porte del controller
** spese generali associate al trasferimento dei dati all'archivio oggetti in caso di FabricPool
** latenza applicata automaticamente da QoS per mantenere l'IO entro i massimi livelli di servizio delle prestazioni


* I valori di latenza non sono applicabili alle operazioni di scrittura MetroCluster .  Queste operazioni di scrittura dipendono dalla distanza dei sistemi remoti.
* Se a uno o più volumi di un sistema di storage non è assegnata una policy AQoS, tali volumi vengono considerati non conformi e per tali sistemi non sono applicabili livelli di servizio di prestazioni target.
* _Expected IOPS_ è destinato a FabricPool solo se la policy di tiering è impostata su "none" e non ci sono blocchi nel cloud.  _IOPS previsti_ è destinato ai volumi che non sono in una relazione sincrona SnapMirror .
* Le operazioni di I/O del carico di lavoro devono essere bilanciate tra tutti i controller distribuiti, come determinato dall'ordine Keystone .




== Archiviazione di oggetti

*Protocollo supportato*: S3

|===


| *Livello di servizio prestazionale* | Oggetto 


| *Tipo di carico di lavoro* | Archivio multimediale, archiviazione 


| *IOPS/TiB logici massimi archiviati per volume* | N / A 


| *Massimo MBps/TiB logici archiviati per volume* | N / A 


| *Latenza media* | N / A 


| *Tipo di capacità impegnata e misurata* | Fisico 
|===

NOTE: La latenza non include i costi generali associati al trasferimento dei dati all'archivio oggetti nel caso di archiviazione FabricPool .



== Archiviazione cloud

*Protocollo supportato*: NFS, CIFS, iSCSI e S3 (solo AWS e Azure)

|===


| *Livello di servizio prestazionale* | Cloud Volumes ONTAP 


| *Tipo di carico di lavoro* | Disaster Recovery, sviluppo/test software, applicazioni aziendali 


| *IOPS/TiB logici massimi archiviati per volume* | N / A 


| *Massimo MBps/TiB logici archiviati per volume* | N / A 


| *Latenza media* | N / A 
|===
[NOTE]
====
* I servizi cloud nativi, come elaborazione, archiviazione e networking, vengono fatturati dai provider cloud.
* Questi servizi dipendono dalle caratteristiche di archiviazione e di elaborazione nel cloud.


====
*Informazioni correlate*

* link:../concepts/supported-storage-capacity.html["Capacità di archiviazione supportate"]
* link:..//concepts/metrics.html["Metriche e definizioni utilizzate nei servizi Keystone"]
* link:../concepts/qos.html["Qualità del servizio (QoS) a Keystone"]
* link:../concepts/pricing.html["Prezzi Keystone"]

