---
sidebar: sidebar 
permalink: installation/install-itom-linux.html 
keywords: Linux installation, ITOM Collector installation 
summary: Installare il software ITOM Collector sui sistemi basati su Linux. 
---
= Installa ITOM Collector sui sistemi Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Completa alcuni passaggi per installare ITOM Collector, che raccoglie i dati delle metriche nel tuo ambiente di archiviazione.  È possibile installarlo su sistemi Windows o Linux, a seconda delle proprie esigenze.


NOTE: Il team di supporto Keystone fornisce un collegamento dinamico per scaricare il file di installazione di ITOM Collector, che scade tra due ore.

Per installare ITOM Collector sui sistemi Windows, fare riferimento alink:../installation/install-itom-windows.html["Installa ITOM Collector sui sistemi Windows"] .

Per installare il software sul tuo server Linux, segui questi passaggi:

.Prima di iniziare
* Verificare che la shell Bourne sia disponibile per lo script di installazione di Linux.
* Installare il `vim-common` pacchetto per ottenere il binario *xxd* necessario per il file di installazione di ITOM Collector.
* Assicurare il `sudo package` è installato se si prevede di eseguire ITOM Collector come utente non root.


.Passi
. Scarica il file di installazione di ITOM Collector sul tuo server Linux.
. Aprire un terminale sul server ed eseguire il seguente comando per modificare i permessi e rendere eseguibili i file binari:
`# chmod +x <installer_file_name>.bin`
. Eseguire il comando per avviare il file di installazione del collettore ITOM:
`#./<installer_file_name>.bin`
. L'esecuzione del file di installazione richiede di:
+
.. Accettare il contratto di licenza con l'utente finale (EULA).
.. Inserisci i dettagli dell'utente per l'installazione.
.. Specificare la directory padre di installazione.
.. Selezionare la dimensione del collettore.
.. Se applicabile, fornire i dettagli del proxy.
+
Per ogni richiesta viene visualizzata un'opzione predefinita.  Si consiglia di selezionare l'opzione predefinita, a meno che non si abbiano esigenze specifiche.  Premere il tasto *Invio* per scegliere l'opzione predefinita.  Al termine dell'installazione, un messaggio conferma che ITOM Collector è stato installato correttamente.





[NOTE]
====
* Il file di installazione di ITOM Collector apporta aggiunte a `/etc/sudoers` per gestire i riavvii dei servizi e i dump della memoria.
* L'installazione di ITOM Collector sul server Linux crea un utente predefinito denominato *ITOM* per eseguire ITOM Collector senza privilegi di root.  È possibile scegliere un utente diverso o eseguirlo come root, ma è consigliabile utilizzare l'utente ITOM creato dallo script di installazione di Linux.


====
.Cosa succederà ora?
Una volta completata l'installazione, contattare il team di supporto Keystone per convalidare la corretta installazione di ITOM Collector tramite il portale di supporto ITOM.  Dopo la verifica, il team di supporto Keystone configurerà ITOM Collector da remoto, inclusa l'ulteriore configurazione del rilevamento e del monitoraggio dei dispositivi, e invierà una conferma una volta completata la configurazione.  Per qualsiasi domanda o informazione aggiuntiva, contattare keystone.services@netapp.com.
