---
sidebar: sidebar 
permalink: installation/validation.html 
keywords: validate, validation 
summary: 'Il repository Keystone è configurato per convalidare automaticamente l"integrità del software Keystone .' 
---
= Validazione automatica del software Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il repository Keystone è configurato per convalidare automaticamente l'integrità del software Keystone , in modo che nel tuo sito vengano installati solo software validi e autentici.

La configurazione del client del repository Keystone YUM fornita in `keystonerepo.rpm` utilizza il controllo GPG forzato(`gpgcheck=1` ) su tutti i software scaricati tramite questo repository.  Qualsiasi RPM scaricato tramite il repository Keystone che non supera la convalida della firma non potrà essere installato.  Questa funzionalità viene utilizzata nella funzionalità di aggiornamento automatico programmato di Keystone Collector per garantire che nel tuo sito vengano installati solo software validi e autentici.
